### ISSUE TITLE
[BUG]: fix the container div height

### ISSUE THREAD

**Issue by Kira272921** [Kira272921/vscode-themed-portfolio#1]
In the [Projects](https://www.kiradev.co/projects) page, on smaller screens the container height is small. Due to this the white color is been seen 

![image](https://user-images.githubusercontent.com/90365542/150344951-c179f7f7-778a-43f2-a92f-190696e36eff.png)

**Comment by sri-nivas1227** [comment]
I can't the projects.md file in the repo. where is it?

**Comment by Kira272921** [comment]
@sri-nivas1227 Here is the link to the `Project` container https://github.com/Kira272921/vscode-themed-portfolio/blob/main/components/Content/Projects.jsx

**Comment by sri-nivas1227** [comment]
@Kira272921, The white color is not only for the projects page, it is happening for all the other pages too.

**Comment by Kira272921** [comment]
@sri-nivas1227 ohh... it is happening due to the height of the gray container

**Comment by sri-nivas1227** [comment]
yeah.... The white layer is starting when the screen size is reduced under 502px. have you observed that?

**Comment by Kira272921** [comment]
yep 👍

**Comment by sri-nivas1227** [comment]
I am new to React and I looked through the tailwind docs.
 I observed that the class-name "h-[100vh]" is similar to "h-screen" and it is only working till 500px screen height.
I think we can use the class name "h-max" when the screen height reaches 500px, then we can get rid of the white color thing.

**Comment by Kira272921** [comment]
@sri-nivas1227 I have fixed this issue 😄. Thanks a lot for taking your taking out to work on this issue 🎉

**Comment by sri-nivas1227** [comment]
Awesome....  I'm glad that I could help.
