### ISSUE TITLE
[FEAT] Add codeowners file to auto assign Kira as reviewer to PR's

### ISSUE THREAD

**Issue by KendallDoesCoding** [Kira272921/vscode-themed-portfolio#15]

**Comment by Kira272921** [comment]
@KendallDoesCoding Hey! Do you want to work on this issue ?

**Comment by KendallDoesCoding** [comment]
> @KendallDoesCoding Hey! Do you want to work on this issue ?

Yup ofc. It's just one line of code, I didn't get to work because I was awaiting your approval. If your down with the idea, will make a PR shortly.

**Comment by KendallDoesCoding** [comment]
> Alright, Thanks a lot @KendallDoesCoding

Will work on this and make a PR in about 30 mins - 1 hour
