### ISSUE TITLE
[DOCS] add an using guide in `README.md`

### ISSUE THREAD

**Issue by Kira272921** [Kira272921/vscode-themed-portfolio#4]
Add a new section about "How to use this portfolio template" in `README.md`.

You might add these following steps in the using guide:
- Cloning the repository
- Installing the dependencies
-  Add the data in [data.json](https://github.com/Kira272921/vscode-themed-portfolio/blob/main/data/data.json) file
- Starting a local development server to preview the changes

**Comment by saugatrajbhandari** [comment]
i can do it. assign this task to me

**Comment by Kira272921** [comment]
@saugatrajbhandari Alright 👍. Assigning it to you :D

**Comment by rishabh1y** [comment]
Hi @Kira272921 Hope you are fine..I am a beginner with Open Source and would love to contribute to this good first issue. Please Assign the task to me

**Comment by Kira272921** [comment]
@rishabh1y Hey! Welcome to Open Source community :D. As @saugatrajbhandari have removed their assignment, I will assign
