### ISSUE TITLE
[FEAT] add issue and pull request template

### ISSUE THREAD

**Issue by Kira272921** [Kira272921/vscode-themed-portfolio#5]
Here are the docs which might be helpful for creating issue and pull request templates 👇

- [How to create an issue template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/manually-creating-a-single-issue-template-for-your-repository )
- [How to create pull request template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)

**Comment by divyakelaskar** [comment]
I would like to work on this 🚀

**Comment by Kira272921** [comment]
@divyakelaskar Thanks :D. I'll assign you

**Comment by Kira272921** [comment]
@divyakelaskar Hey! I am un-assigning you there was no response from your side since a long time. Let me know if you still want to work on this issue

**Comment by divyakelaskar** [comment]
> @divyakelaskar Hey! I am un-assigning you there was no response from your side since a long time. Let me know if you still want to work on this issue

All good... looks like I won't be able to work the issue as of now.

Happy Hacking !

**Comment by TechStudent11** [comment]
@Kira272921 this seems easy enough. Just do you want a template or issue form? There are differences.

**Comment by Kira272921** [comment]
@TechStudent11 Just a template

**Comment by TechStudent11** [comment]
> @TechStudent11 Just a template

Okay, I'll create a PR.

**Comment by KendallDoesCoding** [comment]
@Kira272921 I can work on the PR template, if needed. Please let me know.

**Comment by Kira272921** [comment]
> > @TechStudent11 Just a template
> 
> Okay, I'll create a PR.

Thanks!

**Comment by Kira272921** [comment]
> @Kira272921 I can work on the PR template, if needed. Please let me know.

Thanks a lot. Just create a PR I'll take a look at it

**Comment by KendallDoesCoding** [comment]
> > @Kira272921 I can work on the PR template, if needed. Please let me know.
> 
> Thanks a lot. Just create a PR I'll take a look at it

Will do shortly, maybe tommrow. Thanks

**Comment by KendallDoesCoding** [comment]
> > > @TechStudent11 Just a template
> > 
> > 
> > Okay, I'll create a PR.
> 
> Thanks!

They made a PR #13

**Comment by Kira272921** [comment]
> They made a PR #13

Yep just saw it

**Comment by KendallDoesCoding** [comment]
@Kira272921 Don't close it yet as only the issue template is complete, not the PR template 😆

**Comment by TechStudent11** [comment]
> @Kira272921 Don't close it yet as only the issue template is complete, not the PR template 😆

no need for that

**Comment by TechStudent11** [comment]
Just re-read the title. Maybe put that into a separate issue.

**Comment by KendallDoesCoding** [comment]
> Just re-read the title. Maybe put that into a separate issue.

Yeah maybe. I'll work on adding a feature request template and on the PR template, either after dinner or sometime tommrow.

**Comment by Kira272921** [comment]
> @Kira272921 Don't close it yet as only the issue template is complete, not the PR template 😆

Ahh yep, I'm sorry
